name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compilers
      run: sudo apt-get install clang gcc-multilib
    - name: adsf
      run: cat /proc/cpuinfo
    - name: make
      run: make clean fec_test
