name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compilers
      run: apt install clang
    - name: adsf
      run: echo asdfdf
    - name: make
      run: make clean build/fec_test.elf
