name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compilers
      run: sudo apt-get clang
    - name: adsf
      run: echo asdfdfsdf
    - name: make
      run: make clean build/fec_test.elf
